export const PLANETS = [
  {
    id: "mercury",
    name: "Mercury",
    radius: 0.38,
    distance: 5.5,
    orbitSpeed: 4.74,
    rotationSpeed: 0.003,
    color: "#b5b5b5",
    emissive: "#1a1a1a",
    roughness: 0.9,
    metalness: 0.1,
    description: "The smallest planet and closest to the Sun, Mercury has extreme temperature swings — scorching by day, freezing by night — with no atmosphere to moderate them.",
    stats: {
      diameter: "4,879 km",
      mass: "3.30 × 10²³ kg",
      distanceFromSun: "57.9M km",
      orbitalPeriod: "88 Earth days",
      dayLength: "58.6 Earth days",
      avgTemp: "167°C",
      moons: 0,
      gravity: "3.7 m/s²",
    },
    color2: "#8c7c6e",
    rings: false,
  },
  {
    id: "venus",
    name: "Venus",
    radius: 0.95,
    distance: 8.5,
    orbitSpeed: 3.5,
    rotationSpeed: 0.002,
    color: "#e8cda0",
    emissive: "#3d2a00",
    roughness: 0.7,
    metalness: 0.0,
    description: "Shrouded in thick clouds of sulfuric acid, Venus is the hottest planet due to a runaway greenhouse effect. It rotates backwards compared to most planets.",
    stats: {
      diameter: "12,104 km",
      mass: "4.87 × 10²⁴ kg",
      distanceFromSun: "108.2M km",
      orbitalPeriod: "225 Earth days",
      dayLength: "243 Earth days",
      avgTemp: "464°C",
      moons: 0,
      gravity: "8.87 m/s²",
    },
    color2: "#c4a46a",
    rings: false,
  },
  {
    id: "earth",
    name: "Earth",
    radius: 1.0,
    distance: 12.0,
    orbitSpeed: 2.98,
    rotationSpeed: 0.005,
    color: "#4b9cd3",
    emissive: "#001a2e",
    roughness: 0.5,
    metalness: 0.1,
    description: "Our home planet — the only known world to harbor life. Earth's liquid water, oxygen atmosphere, and magnetic field create a perfect haven for complex organisms.",
    stats: {
      diameter: "12,742 km",
      mass: "5.97 × 10²⁴ kg",
      distanceFromSun: "149.6M km",
      orbitalPeriod: "365.25 days",
      dayLength: "24 hours",
      avgTemp: "15°C",
      moons: 1,
      gravity: "9.81 m/s²",
    },
    color2: "#2d7a3a",
    rings: false,
  },
  {
    id: "mars",
    name: "Mars",
    radius: 0.53,
    distance: 16.5,
    orbitSpeed: 2.41,
    rotationSpeed: 0.005,
    color: "#c1440e",
    emissive: "#3d1000",
    roughness: 0.95,
    metalness: 0.0,
    description: "The Red Planet hosts the tallest volcano and deepest canyon in the solar system. Mars has seasons, polar ice caps, and evidence of ancient liquid water.",
    stats: {
      diameter: "6,779 km",
      mass: "6.39 × 10²³ kg",
      distanceFromSun: "227.9M km",
      orbitalPeriod: "687 Earth days",
      dayLength: "24.6 hours",
      avgTemp: "-65°C",
      moons: 2,
      gravity: "3.72 m/s²",
    },
    color2: "#a0522d",
    rings: false,
  },
  {
    id: "jupiter",
    name: "Jupiter",
    radius: 2.8,
    distance: 24.0,
    orbitSpeed: 1.31,
    rotationSpeed: 0.012,
    color: "#c88b3a",
    emissive: "#1a0800",
    roughness: 0.6,
    metalness: 0.0,
    description: "The largest planet — a gas giant 1,300 Earths could fit inside. Jupiter's Great Red Spot is a storm larger than Earth that has raged for centuries.",
    stats: {
      diameter: "139,820 km",
      mass: "1.90 × 10²⁷ kg",
      distanceFromSun: "778.5M km",
      orbitalPeriod: "11.9 Earth years",
      dayLength: "9.9 hours",
      avgTemp: "-110°C",
      moons: 95,
      gravity: "24.79 m/s²",
    },
    color2: "#a0522d",
    rings: false,
  },
  {
    id: "saturn",
    name: "Saturn",
    radius: 2.3,
    distance: 33.0,
    orbitSpeed: 0.97,
    rotationSpeed: 0.01,
    color: "#e4d191",
    emissive: "#1a1500",
    roughness: 0.5,
    metalness: 0.0,
    description: "Famous for its spectacular ring system made of ice and rock, Saturn is the least dense planet — it would float on water. Its moon Titan has a thick atmosphere.",
    stats: {
      diameter: "116,460 km",
      mass: "5.68 × 10²⁶ kg",
      distanceFromSun: "1.43B km",
      orbitalPeriod: "29.5 Earth years",
      dayLength: "10.7 hours",
      avgTemp: "-140°C",
      moons: 146,
      gravity: "10.44 m/s²",
    },
    color2: "#c4a85a",
    rings: true,
    ringInner: 3.2,
    ringOuter: 5.2,
    ringColor: "#c8b882",
    ringOpacity: 0.7,
  },
  {
    id: "uranus",
    name: "Uranus",
    radius: 1.6,
    distance: 42.0,
    orbitSpeed: 0.68,
    rotationSpeed: 0.007,
    color: "#7de8e8",
    emissive: "#002222",
    roughness: 0.4,
    metalness: 0.1,
    description: "An ice giant tilted on its side — Uranus rotates nearly perpendicular to its orbit, possibly after a massive ancient collision. Its rings are perpendicular to its orbit.",
    stats: {
      diameter: "50,724 km",
      mass: "8.68 × 10²⁵ kg",
      distanceFromSun: "2.87B km",
      orbitalPeriod: "84 Earth years",
      dayLength: "17.2 hours",
      avgTemp: "-195°C",
      moons: 28,
      gravity: "8.87 m/s²",
    },
    color2: "#5cc8d0",
    rings: true,
    ringInner: 2.0,
    ringOuter: 2.6,
    ringColor: "#9ad0d8",
    ringOpacity: 0.3,
  },
  {
    id: "neptune",
    name: "Neptune",
    radius: 1.55,
    distance: 51.0,
    orbitSpeed: 0.54,
    rotationSpeed: 0.008,
    color: "#3f54ba",
    emissive: "#000820",
    roughness: 0.4,
    metalness: 0.1,
    description: "The windiest planet, Neptune has storms with winds reaching 2,100 km/h. Its large moon Triton orbits backwards and is likely a captured Kuiper Belt object.",
    stats: {
      diameter: "49,244 km",
      mass: "1.02 × 10²⁶ kg",
      distanceFromSun: "4.50B km",
      orbitalPeriod: "165 Earth years",
      dayLength: "16.1 hours",
      avgTemp: "-200°C",
      moons: 16,
      gravity: "11.15 m/s²",
    },
    color2: "#2244aa",
    rings: false,
  },
];

export const SUN_DATA = {
  name: "The Sun",
  radius: 3.5,
  description: "Our star — a massive ball of plasma held together by gravity. The Sun contains 99.86% of all mass in the solar system and drives all weather and life on Earth.",
  stats: {
    diameter: "1,391,400 km",
    mass: "1.99 × 10³⁰ kg",
    surfaceTemp: "5,500°C",
    coreTemp: "15,000,000°C",
    age: "4.6 Billion years",
    type: "G-type main sequence",
    luminosity: "3.83 × 10²⁶ W",
    rotation: "25–36 days",
  },
};
